# resolve-type-names: false

class ::Allcolumn < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::Allcolumn, ::Allcolumn::ActiveRecord_Relation, ::Integer]

  module ::Allcolumn::GeneratedAliasAttributeMethods
    include ::Allcolumn::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::Allcolumn::GeneratedAliasAttributeMethods

  module ::Allcolumn::GeneratedAssociationMethods
  end
  include ::Allcolumn::GeneratedAssociationMethods

  module ::Allcolumn::GeneratedRelationMethods
  end

  class ::Allcolumn::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::Allcolumn]
    include ::Allcolumn::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Allcolumn, ::Integer]
  end

  class ::Allcolumn::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::Allcolumn]
    include ::Allcolumn::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Allcolumn, ::Integer]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Allcolumn
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Allcolumn]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Allcolumn
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Allcolumn]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Allcolumn
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Allcolumn]
    def reload: () -> ::Array[::Allcolumn]

    def replace: (::Array[::Allcolumn]) -> void
    def delete: (*::Allcolumn | ::Integer) -> ::Array[::Allcolumn]
    def destroy: (*::Allcolumn | ::Integer) -> ::Array[::Allcolumn]
    def <<: (*::Allcolumn | ::Array[::Allcolumn]) -> self
    def prepend: (*::Allcolumn | ::Array[::Allcolumn]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
