# resolve-type-names: false

class ::Session < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::Session, ::Session::ActiveRecord_Relation, ::Integer]

  module ::Session::GeneratedAliasAttributeMethods
    include ::Session::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::Session::GeneratedAliasAttributeMethods

  def user: () -> ::User
  def user=: (::User?) -> ::User?
  def reload_user: () -> ::User?
  def build_user: (untyped) -> ::User
  def create_user: (untyped) -> ::User
  def create_user!: (untyped) -> ::User
  module ::Session::GeneratedAssociationMethods
  end
  include ::Session::GeneratedAssociationMethods

  module ::Session::GeneratedRelationMethods
  end

  class ::Session::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::Session]
    include ::Session::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Session, ::Integer]
  end

  class ::Session::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::Session]
    include ::Session::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Session, ::Integer]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Session
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Session]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Session
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Session]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Session
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Session]
    def reload: () -> ::Array[::Session]

    def replace: (::Array[::Session]) -> void
    def delete: (*::Session | ::Integer) -> ::Array[::Session]
    def destroy: (*::Session | ::Integer) -> ::Array[::Session]
    def <<: (*::Session | ::Array[::Session]) -> self
    def prepend: (*::Session | ::Array[::Session]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::User < ::ApplicationRecord
end
