# resolve-type-names: false

class ::User < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::User, ::User::ActiveRecord_Relation, ::Integer]

  module ::User::GeneratedAttributeMethods
    def id: () -> ::Integer

    def id=: (::Integer) -> ::Integer

    def id?: () -> bool

    def id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def id_change: () -> [ ::Integer?, ::Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> ::Integer?

    def id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def id_previous_change: () -> ::Array[::Integer?]?

    def id_previously_was: () -> ::Integer?

    def id_before_last_save: () -> ::Integer?

    def id_change_to_be_saved: () -> ::Array[::Integer?]?

    def id_in_database: () -> ::Integer?

    def saved_change_to_id: () -> ::Array[::Integer?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::Integer

    def id_for_database: () -> ::Integer
  end
  include ::User::GeneratedAttributeMethods
  module ::User::GeneratedAliasAttributeMethods
    include ::User::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::User::GeneratedAliasAttributeMethods
  def sessions: () -> ::Session::ActiveRecord_Associations_CollectionProxy
  def sessions=: (::Session::ActiveRecord_Associations_CollectionProxy | ::Array[::Session]) -> (::Session::ActiveRecord_Associations_CollectionProxy | ::Array[::Session])
  def session_ids: () -> ::Array[::Integer]
  def session_ids=: (::Array[::Integer]) -> ::Array[::Integer]
  def articles: () -> ::Article::ActiveRecord_Associations_CollectionProxy
  def articles=: (::Article::ActiveRecord_Associations_CollectionProxy | ::Array[::Article]) -> (::Article::ActiveRecord_Associations_CollectionProxy | ::Array[::Article])
  def article_ids: () -> ::Array[::Integer]
  def article_ids=: (::Array[::Integer]) -> ::Array[::Integer]

  module ::User::GeneratedAssociationMethods
  end
  include ::User::GeneratedAssociationMethods
  module ::User::ActiveModel_SecurePassword_InstanceMethodsOnActivation_password
    attr_reader password: ::String?

    def password=: (::String) -> ::String

    def password_confirmation=: (::String) -> ::String

    def authenticate_password: (::String) -> (::User | false)

    alias authenticate authenticate_password
  end
  include ::User::ActiveModel_SecurePassword_InstanceMethodsOnActivation_password

  module ::User::GeneratedRelationMethods
  end

  class ::User::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::User]
    include ::User::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::User, ::Integer]
  end

  class ::User::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::User]
    include ::User::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::User, ::Integer]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::User
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::User]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::User
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::User]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::User
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::User]
    def reload: () -> ::Array[::User]

    def replace: (::Array[::User]) -> void
    def delete: (*::User | ::Integer) -> ::Array[::User]
    def destroy: (*::User | ::Integer) -> ::Array[::User]
    def <<: (*::User | ::Array[::User]) -> self
    def prepend: (*::User | ::Array[::User]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::Session < ::ApplicationRecord
end
class ::Session::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::Article < ::ApplicationRecord
end
class ::Article::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
