# In schema.rb, this model is declared as:
#
# ```ruby
# create_table "allcolumns", force: :cascade do |t|
#   t.binary "cbinary"
#   t.boolean "cboolean"
#   t.date "cdate"
#   t.datetime "cdatetime"
#   t.decimal "cdecimal"
#   t.float "cfloat"
#   t.integer "cinteger"
#   t.json "cjson"
#   t.datetime "created_at", null: false
#   t.string "cstring"
#   t.text "ctext"
#   t.time "ctime"
#   t.timestamp "ctimestamp"
#   t.virtual "cvirtual_int", type: :integer, as: "length(cstring)", stored: true
#   t.virtual "cvirtual_str", type: :string, as: "cstring || ctext", stored: true
#   t.datetime "updated_at", null: false
# end
# ```
class Allcolumn
  include GeneratedAttributeMethods

  module GeneratedAttributeMethods
    # ```ruby
    # t.binary "cbinary"
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def cbinary: () -> ::String?

    # ```ruby
    # t.binary "cbinary"
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def cbinary=: (::String? value) -> void

    # ```ruby
    # t.binary "cbinary"
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def cbinary_before_type_cast: () -> untyped

    # ```ruby
    # t.binary "cbinary"
    # ```
    #
    def cbinary_for_database: () -> untyped

    # ```ruby
    # t.boolean "cboolean"
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def cboolean: () -> bool?

    # ```ruby
    # t.boolean "cboolean"
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def cboolean=: (bool? value) -> void

    # ```ruby
    # t.boolean "cboolean"
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def cboolean_before_type_cast: () -> untyped

    # ```ruby
    # t.boolean "cboolean"
    # ```
    #
    def cboolean_for_database: () -> untyped

    # ```ruby
    # t.date "cdate"
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def cdate: () -> ::Date?

    # ```ruby
    # t.date "cdate"
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def cdate=: (::Date? value) -> void

    # ```ruby
    # t.date "cdate"
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def cdate_before_type_cast: () -> untyped

    # ```ruby
    # t.date "cdate"
    # ```
    #
    def cdate_for_database: () -> untyped

    # ```ruby
    # t.datetime "cdatetime"
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def cdatetime: () -> ::ActiveSupport::TimeWithZone?

    # ```ruby
    # t.datetime "cdatetime"
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def cdatetime=: (::ActiveSupport::TimeWithZone? value) -> void

    # ```ruby
    # t.datetime "cdatetime"
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def cdatetime_before_type_cast: () -> untyped

    # ```ruby
    # t.datetime "cdatetime"
    # ```
    #
    def cdatetime_for_database: () -> untyped

    # ```ruby
    # t.decimal "cdecimal"
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def cdecimal: () -> ::BigDecimal?

    # ```ruby
    # t.decimal "cdecimal"
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def cdecimal=: (::BigDecimal? value) -> void

    # ```ruby
    # t.decimal "cdecimal"
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def cdecimal_before_type_cast: () -> untyped

    # ```ruby
    # t.decimal "cdecimal"
    # ```
    #
    def cdecimal_for_database: () -> untyped

    # ```ruby
    # t.float "cfloat"
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def cfloat: () -> ::Float?

    # ```ruby
    # t.float "cfloat"
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def cfloat=: (::Float? value) -> void

    # ```ruby
    # t.float "cfloat"
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def cfloat_before_type_cast: () -> untyped

    # ```ruby
    # t.float "cfloat"
    # ```
    #
    def cfloat_for_database: () -> untyped

    # ```ruby
    # t.integer "cinteger"
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def cinteger: () -> ::Integer?

    # ```ruby
    # t.integer "cinteger"
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def cinteger=: (::Integer? value) -> void

    # ```ruby
    # t.integer "cinteger"
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def cinteger_before_type_cast: () -> untyped

    # ```ruby
    # t.integer "cinteger"
    # ```
    #
    def cinteger_for_database: () -> untyped

    # ```ruby
    # t.json "cjson"
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def cjson: () -> untyped?

    # ```ruby
    # t.json "cjson"
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def cjson=: (untyped? value) -> void

    # ```ruby
    # t.json "cjson"
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def cjson_before_type_cast: () -> untyped

    # ```ruby
    # t.json "cjson"
    # ```
    #
    def cjson_for_database: () -> untyped

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def created_at: () -> ::ActiveSupport::TimeWithZone

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def created_at=: (::ActiveSupport::TimeWithZone value) -> void

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def created_at_before_type_cast: () -> untyped

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    def created_at_for_database: () -> untyped

    # ```ruby
    # t.string "cstring"
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def cstring: () -> ::String?

    # ```ruby
    # t.string "cstring"
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def cstring=: (::String? value) -> void

    # ```ruby
    # t.string "cstring"
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def cstring_before_type_cast: () -> untyped

    # ```ruby
    # t.string "cstring"
    # ```
    #
    def cstring_for_database: () -> untyped

    # ```ruby
    # t.text "ctext"
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def ctext: () -> ::String?

    # ```ruby
    # t.text "ctext"
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def ctext=: (::String? value) -> void

    # ```ruby
    # t.text "ctext"
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def ctext_before_type_cast: () -> untyped

    # ```ruby
    # t.text "ctext"
    # ```
    #
    def ctext_for_database: () -> untyped

    # ```ruby
    # t.time "ctime"
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def ctime: () -> ::ActiveSupport::TimeWithZone?

    # ```ruby
    # t.time "ctime"
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def ctime=: (::ActiveSupport::TimeWithZone? value) -> void

    # ```ruby
    # t.time "ctime"
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def ctime_before_type_cast: () -> untyped

    # ```ruby
    # t.time "ctime"
    # ```
    #
    def ctime_for_database: () -> untyped

    # ```ruby
    # t.timestamp "ctimestamp"
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def ctimestamp: () -> ::ActiveSupport::TimeWithZone?

    # ```ruby
    # t.timestamp "ctimestamp"
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def ctimestamp=: (::ActiveSupport::TimeWithZone? value) -> void

    # ```ruby
    # t.timestamp "ctimestamp"
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def ctimestamp_before_type_cast: () -> untyped

    # ```ruby
    # t.timestamp "ctimestamp"
    # ```
    #
    def ctimestamp_for_database: () -> untyped

    # ```ruby
    # t.virtual "cvirtual_int", type: :integer, as: "length(cstring)", stored: true
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def cvirtual_int: () -> ::Integer?

    # ```ruby
    # t.virtual "cvirtual_int", type: :integer, as: "length(cstring)", stored: true
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def cvirtual_int=: (::Integer? value) -> void

    # ```ruby
    # t.virtual "cvirtual_int", type: :integer, as: "length(cstring)", stored: true
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def cvirtual_int_before_type_cast: () -> untyped

    # ```ruby
    # t.virtual "cvirtual_int", type: :integer, as: "length(cstring)", stored: true
    # ```
    #
    def cvirtual_int_for_database: () -> untyped

    # ```ruby
    # t.virtual "cvirtual_str", type: :string, as: "cstring || ctext", stored: true
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def cvirtual_str: () -> ::String?

    # ```ruby
    # t.virtual "cvirtual_str", type: :string, as: "cstring || ctext", stored: true
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def cvirtual_str=: (::String? value) -> void

    # ```ruby
    # t.virtual "cvirtual_str", type: :string, as: "cstring || ctext", stored: true
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def cvirtual_str_before_type_cast: () -> untyped

    # ```ruby
    # t.virtual "cvirtual_str", type: :string, as: "cstring || ctext", stored: true
    # ```
    #
    def cvirtual_str_for_database: () -> untyped

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def updated_at: () -> ::ActiveSupport::TimeWithZone

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def updated_at=: (::ActiveSupport::TimeWithZone value) -> void

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def updated_at_before_type_cast: () -> untyped

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    def updated_at_for_database: () -> untyped
  end
end

# In schema.rb, this model is declared as:
#
# ```ruby
# create_table "articles", force: :cascade do |t|
#   t.text "body"
#   t.datetime "created_at", null: false
#   t.string "title"
#   t.datetime "updated_at", null: false
#   t.integer "user_id"
#   t.index ["user_id"], name: "index_articles_on_user_id"
# end
# ```
class Article
  include GeneratedAttributeMethods

  module GeneratedAttributeMethods
    # ```ruby
    # t.text "body"
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def body: () -> ::String?

    # ```ruby
    # t.text "body"
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def body=: (::String? value) -> void

    # ```ruby
    # t.text "body"
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def body_before_type_cast: () -> untyped

    # ```ruby
    # t.text "body"
    # ```
    #
    def body_for_database: () -> untyped

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def created_at: () -> ::ActiveSupport::TimeWithZone

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def created_at=: (::ActiveSupport::TimeWithZone value) -> void

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def created_at_before_type_cast: () -> untyped

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    def created_at_for_database: () -> untyped

    # ```ruby
    # t.string "title"
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def title: () -> ::String?

    # ```ruby
    # t.string "title"
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def title=: (::String? value) -> void

    # ```ruby
    # t.string "title"
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def title_before_type_cast: () -> untyped

    # ```ruby
    # t.string "title"
    # ```
    #
    def title_for_database: () -> untyped

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def updated_at: () -> ::ActiveSupport::TimeWithZone

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def updated_at=: (::ActiveSupport::TimeWithZone value) -> void

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def updated_at_before_type_cast: () -> untyped

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    def updated_at_for_database: () -> untyped

    # ```ruby
    # t.integer "user_id"
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def user_id: () -> ::Integer?

    # ```ruby
    # t.integer "user_id"
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def user_id=: (::Integer? value) -> void

    # ```ruby
    # t.integer "user_id"
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def user_id_before_type_cast: () -> untyped

    # ```ruby
    # t.integer "user_id"
    # ```
    #
    def user_id_for_database: () -> untyped
  end
end

# In schema.rb, this model is declared as:
#
# ```ruby
# create_table "sessions", force: :cascade do |t|
#   t.datetime "created_at", null: false
#   t.string "ip_address"
#   t.datetime "updated_at", null: false
#   t.string "user_agent"
#   t.integer "user_id", null: false
#   t.index ["user_id"], name: "index_sessions_on_user_id"
# end
# ```
class Session
  include GeneratedAttributeMethods

  module GeneratedAttributeMethods
    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def created_at: () -> ::ActiveSupport::TimeWithZone

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def created_at=: (::ActiveSupport::TimeWithZone value) -> void

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def created_at_before_type_cast: () -> untyped

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    def created_at_for_database: () -> untyped

    # ```ruby
    # t.string "ip_address"
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def ip_address: () -> ::String?

    # ```ruby
    # t.string "ip_address"
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def ip_address=: (::String? value) -> void

    # ```ruby
    # t.string "ip_address"
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def ip_address_before_type_cast: () -> untyped

    # ```ruby
    # t.string "ip_address"
    # ```
    #
    def ip_address_for_database: () -> untyped

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def updated_at: () -> ::ActiveSupport::TimeWithZone

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def updated_at=: (::ActiveSupport::TimeWithZone value) -> void

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def updated_at_before_type_cast: () -> untyped

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    def updated_at_for_database: () -> untyped

    # ```ruby
    # t.string "user_agent"
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def user_agent: () -> ::String?

    # ```ruby
    # t.string "user_agent"
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def user_agent=: (::String? value) -> void

    # ```ruby
    # t.string "user_agent"
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def user_agent_before_type_cast: () -> untyped

    # ```ruby
    # t.string "user_agent"
    # ```
    #
    def user_agent_for_database: () -> untyped

    # ```ruby
    # t.integer "user_id", null: false
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def user_id: () -> ::Integer

    # ```ruby
    # t.integer "user_id", null: false
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def user_id=: (::Integer value) -> void

    # ```ruby
    # t.integer "user_id", null: false
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def user_id_before_type_cast: () -> untyped

    # ```ruby
    # t.integer "user_id", null: false
    # ```
    #
    def user_id_for_database: () -> untyped
  end
end

# In schema.rb, this model is declared as:
#
# ```ruby
# create_table "users", force: :cascade do |t|
#   t.datetime "created_at", null: false
#   t.string "email_address", null: false
#   t.string "password_digest", null: false
#   t.datetime "updated_at", null: false
#   t.index ["email_address"], name: "index_users_on_email_address", unique: true
# end
# ```
class User
  include GeneratedAttributeMethods

  module GeneratedAttributeMethods
    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def created_at: () -> ::ActiveSupport::TimeWithZone

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def created_at=: (::ActiveSupport::TimeWithZone value) -> void

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def created_at_before_type_cast: () -> untyped

    # ```ruby
    # t.datetime "created_at", null: false
    # ```
    #
    def created_at_for_database: () -> untyped

    # ```ruby
    # t.string "email_address", null: false
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def email_address: () -> ::String

    # ```ruby
    # t.string "email_address", null: false
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def email_address=: (::String value) -> void

    # ```ruby
    # t.string "email_address", null: false
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def email_address_before_type_cast: () -> untyped

    # ```ruby
    # t.string "email_address", null: false
    # ```
    #
    def email_address_for_database: () -> untyped

    # ```ruby
    # t.string "password_digest", null: false
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def password_digest: () -> ::String

    # ```ruby
    # t.string "password_digest", null: false
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def password_digest=: (::String value) -> void

    # ```ruby
    # t.string "password_digest", null: false
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def password_digest_before_type_cast: () -> untyped

    # ```ruby
    # t.string "password_digest", null: false
    # ```
    #
    def password_digest_for_database: () -> untyped

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    # Returns the value of the attribute identified by <tt>attr_name</tt> after
    # it has been typecast (for example, "2004-12-12" in a date column is cast
    # to a date object, like Date.new(2004, 12, 12)).
    def updated_at: () -> ::ActiveSupport::TimeWithZone

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    # Updates the attribute identified by <tt>attr_name</tt> with the
    # specified +value+. Empty strings for Integer and Float columns are
    # turned into +nil+.
    def updated_at=: (::ActiveSupport::TimeWithZone value) -> void

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    # Returns the value of the attribute identified by +attr_name+ before
    # typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.read_attribute('id')                            # => 1
    #   task.read_attribute_before_type_cast('id')           # => '1'
    #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
    def updated_at_before_type_cast: () -> untyped

    # ```ruby
    # t.datetime "updated_at", null: false
    # ```
    #
    def updated_at_for_database: () -> untyped
  end
end
